networks:
  default:
    name: kong-with-go
    driver: bridge

services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KONG_LOG_LEVEL: info
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yaml
      KONG_PLUGINS: cors,bundled,path-prefix
      KONG_PLUGINSERVER_NAMES: path-prefix
      KONG_PLUGINSERVER_PATH_PREFIX_QUERY_CMD: path-prefix --dump
    privileged: true
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./kong.yaml:/home/kong/kong.yaml
  echo:
    image: ealen/echo-server
    environment:
      - PORT=3000
